// Generated by generate-globe-manifest.js
window.globePhotos = [
  "images/globe/Askalany_group (1).webp",
  "images/globe/Askalany_group (2).webp",
  "images/globe/Askalany_group (3).webp",
  "images/globe/Askalany_group (4).webp",
  "images/globe/Askalany_group (5).webp",
  "images/globe/Askalany_group (6).webp",
  "images/globe/Askalany_group (7).webp",
  "images/globe/Askalany_group (8).webp",
  "images/globe/Askalany_group (9).webp",
  "images/globe/Askalany_group (10).webp",
  "images/globe/Askalany_group (11).webp",
  "images/globe/Askalany_group (12).webp",
  "images/globe/Askalany_group (13).webp",
  "images/globe/Askalany_group (14).webp",
  "images/globe/Askalany_group (15).webp",
  "images/globe/Askalany_group (16).webp",
  "images/globe/Askalany_group (17).webp",
  "images/globe/Askalany_group (18).webp"
];
